In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install tensorflow-hub

  Obtaining dependency information for tensorflow-hub from https://files.pythonhosted.org/packages/e5/50/00dba77925bf2a0a1e45d7bcf8a69a1d2534fb4bb277d9010bd148d2235e/tensorflow_hub-0.16.1-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tf-keras>=2.14.1 from https://files.pythonhosted.org/packages/75/aa/cf09f8956d4f276f655b13674e15d8d6015fd832f9689aa9ff2a515781ab/tf_keras-2.16.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.7 MB 6.5 MB/s eta 0:00:01
   ---------------- ----------------------- 0.7/1.7 MB 7.5 MB/s eta 0:00:01
   ------------------------- -------------- 1.1/1.7 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  1.7/1.7 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 9.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install tensorflow-datasets

  Obtaining dependency information for tensorflow-datasets from https://files.pythonhosted.org/packages/fe/18/4865973f5469cfe33bbe1cfc2f1918335eb44f4cc3d316c1bce22c1af2bc/tensorflow_datasets-4.9.4-py3-none-any.whl.metadata
  Obtaining dependency information for dm-tree from https://files.pythonhosted.org/packages/e4/c1/522041457444b67125ac9527208bb3148f63d7dce0a86ffa589ec763a10e/dm_tree-0.1.8-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for etils[enp,epath,etree]>=0.9.0 from https://files.pythonhosted.org/packages/d0/3c/784b5f94bcad62a4167f2347fe1095b627433c22a54aecc4504237494b81/etils-1.8.0-py3-none-any.whl.metadata
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Obtaining dependency information for tensorflow-metadata from https://files.pythonhosted.org/packages/aa/47/91d1eea615b12473853edcbc0db02c94918e498bdf36049dde13bf24100d/tensorflow_metadata-1.15.0-py3-none-any.whl.metadata
  Obtaining dependency i

In [32]:
import numpy as np
import tensorflow_hub as hub
import tensorflow_datasets as tfds


In [15]:
train_data,validation_data,test_data= tfds.load(name="imdb_reviews",split=('train[:60%]','train[60%:]','test'),
                                               as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\acer\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteO4WK31\imdb_reviews-train.…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\acer\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteO4WK31\imdb_reviews-test.t…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\acer\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteO4WK31\imdb_reviews-unsupe…

Dataset imdb_reviews downloaded and prepared to C:\Users\acer\tensorflow_datasets\imdb_reviews\plain_text\1.0.0. Subsequent calls will reuse this data.


In [29]:
train_data

physical_devices = tf.config.list_physical_devices('GPU')

if physical_devices:
    print("GPU is available")
else:
    print("GPU is NOT AVAILABLE")


GPU is NOT AVAILABLE


In [24]:
train_example_batch,train_labels_batch=next(iter(train_data.batch(10)))

In [18]:
train_example_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [19]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)>

In [40]:
import tensorflow_hub as hub
import tensorflow as tf

# Link to a pre-trained word embedding model
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"

# Load the pre-trained embedding model
embed = hub.load(embedding)

# Wrap the embedding model as a Keras layer
hub_layer = hub.KerasLayer(embed, input_shape=[], dtype=tf.string, trainable=True)


In [42]:
import tensorflow_hub as hub
import tensorflow as tf

# Link to a pre-trained word embedding model
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"

# Load the pre-trained embedding model
embed = hub.load(embedding)

# Wrap the embedding model as a Keras layer
hub_layer = hub.KerasLayer(embed, input_shape=[], dtype=tf.string, trainable=True)

# Assuming train_example_batch is your input data
train_example_batch = ["This is example 1.", "This is example 2.", "This is example 3."]  # Define your input data here

# Pass the input data through the hub_layer
output = hub_layer(train_example_batch)  # Pass the entire batch

# Print the output
print(output)



tf.Tensor(
[[-1.8201584e-01  6.6135973e-02  6.1586297e-01  2.7621081e-01
  -9.2503822e-01 -7.8365719e-01 -1.0027633e+00 -9.7254711e-01
   2.1770245e-01 -9.8514849e-01  1.2149322e-01  2.4065316e-01
   6.2876523e-01 -7.2296061e-02  4.6356148e-01 -1.7782323e-01
  -2.1321389e-01  3.4968922e-01  6.9367087e-01 -4.5683402e-01]
 [-9.3900681e-02 -1.6098221e-01  7.2151524e-01  2.1172293e-01
  -1.0198078e+00 -6.6754621e-01 -8.9048904e-01 -8.5254347e-01
   2.9912612e-01 -1.2436192e+00 -3.0475050e-02  2.2940147e-01
   6.3345504e-01 -8.3007507e-02  2.7009702e-01 -2.8577614e-01
  -3.6913961e-01  5.0102216e-01  9.3676770e-01 -4.7339404e-01]
 [-1.3899201e-01 -1.9862145e-01  7.5462997e-01  2.4562323e-01
  -9.5052731e-01 -6.8762594e-01 -8.3523500e-01 -8.4452474e-01
   1.8440229e-01 -1.2317436e+00 -1.0474026e-03  2.4288383e-01
   6.5694189e-01 -5.1190577e-02  2.2006786e-01 -1.8843542e-01
  -4.3437481e-01  3.7426239e-01  9.2145360e-01 -4.0395945e-01]], shape=(3, 20), dtype=float32)


In [48]:
import tensorflow as tf
import tensorflow_hub as hub
hub_layer=hub_layer
model=tf.keras.Sequential()
model.add(tf.keras.layers.Lambda(hub_layer))
model.add(tf.keras.layers.Dense(16,activation='relu'))
model.add(tf.keras.layers.Dense(1))


model.compile(optimizer='adam',
             loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
             metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lambda_2 (Lambda)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [52]:
history=model.fit(train_data.shuffle(10000).batch(100),epochs=25,
                 validation_data=validation_data.batch(100),verbose=1)
import warnings
warnings.filterwarnings("ignore", message="The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Your TensorFlow-related code goes here
import tensorflow as tf


Epoch 1/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7058 - loss: 0.5453 - val_accuracy: 0.7059 - val_loss: 0.5500
Epoch 2/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7146 - loss: 0.5394 - val_accuracy: 0.7073 - val_loss: 0.5501
Epoch 3/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7116 - loss: 0.5422 - val_accuracy: 0.6933 - val_loss: 0.5523
Epoch 4/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7034 - loss: 0.5452 - val_accuracy: 0.7105 - val_loss: 0.5510
Epoch 5/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7155 - loss: 0.5404 - val_accuracy: 0.7000 - val_loss: 0.5495
Epoch 6/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7104 - loss: 0.5425 - val_accuracy: 0.7061 - val_loss: 0.5494
Epoch 7/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7038 - loss: 0.5485 - val_accuracy: 0.7077 - val_loss: 0.5489
Epoch 8/25
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7088 - loss: 0.5404 - val_accuracy: 0.

In [53]:
results=model.evaluate(test_data.batch(100),verbose=2)


for name, values in zip(model.metrics_names,results):
    print("%s: %.3f"%(name,values))

250/250 - 2s - 7ms/step - accuracy: 0.7137 - loss: 0.5540
loss: 0.554
compile_metrics: 0.714
